// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v3.21.12
// source: main_service/comment.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";
import { CommentRes, PaginationRes } from "../base";

export const protobufPackage = "project_service";

export interface CreateCommentReq {
  userId: string;
  content: string;
  issueId: string;
}

export interface CreateCommentRes {
  status: string;
  message: string;
  data: CommentRes | undefined;
}

export interface ListCommentsReq {
  issueId: string;
  page: number;
  limit: number;
}

export interface ListCommentsRes {
  status: string;
  message: string;
  data: CommentRes[];
  pagination: PaginationRes | undefined;
}

export const PROJECT_SERVICE_PACKAGE_NAME = "project_service";

export interface CommentServiceClient {
  createComment(request: CreateCommentReq): Observable<CreateCommentRes>;

  listComments(request: ListCommentsReq): Observable<ListCommentsRes>;
}

export interface CommentServiceController {
  createComment(request: CreateCommentReq): Promise<CreateCommentRes> | Observable<CreateCommentRes> | CreateCommentRes;

  listComments(request: ListCommentsReq): Promise<ListCommentsRes> | Observable<ListCommentsRes> | ListCommentsRes;
}

export function CommentServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["createComment", "listComments"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("CommentService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("CommentService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const COMMENT_SERVICE_NAME = "CommentService";
