// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.5
//   protoc               v3.21.12
// source: main_service/issue.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";
import { ActivityRes, IssueRes, PaginationRes } from "../base";
import { Empty } from "../google/protobuf/empty";

export const protobufPackage = "project_service";

export interface GetActivitiesReq {
  issueId: string;
  page: number;
  limit: number;
}

export interface GetActivitiesRes {
  data: ActivityRes[];
  pagination: PaginationRes | undefined;
}

/** Get by ID */
export interface GetIssueReq {
  id: string;
  projectId: string;
}

/** Delete by ID */
export interface DeleteIssueReq {
  id: string;
  projectId: string;
}

/** Update */
export interface UpdateIssueReq {
  id: string;
  projectId: string;
  sprintId?: string | undefined;
  assigneeId?: string | undefined;
  parentId?: string | undefined;
  reporterId?: string | undefined;
  title?: string | undefined;
  summary?: string | undefined;
  description?: string | undefined;
  type?: string | undefined;
  columnId?: string | undefined;
  priority?: string | undefined;
  storyPoint: number | undefined;
  attachments: string[];
}

/** List All */
export interface ListIssuesReq {
  projectId?: string | undefined;
  columnIds: string[];
  assigneeIds: string[];
  sprintIds: string[];
  keyword?: string | undefined;
  issueIds: string[];
  page: number;
  limit: number;
}

export interface ListIssuesRes {
  data: IssueRes[];
  pagination: PaginationRes | undefined;
}

/** Create */
export interface CreateIssueReq {
  projectId: string;
  title: string;
  sprintId?: string | undefined;
  assigneeId?: string | undefined;
  parentId?: string | undefined;
  reporterId?: string | undefined;
  type: string;
  columnId: string;
  priority: string;
  summary: string;
  description: string;
  storyPoint?: number | undefined;
  attachments: string[];
}

export interface CreateIssueRes {
  data: IssueRes | undefined;
}

export const PROJECT_SERVICE_PACKAGE_NAME = "project_service";

export interface IssueServiceClient {
  createIssue(request: CreateIssueReq): Observable<CreateIssueRes>;

  getIssue(request: GetIssueReq): Observable<IssueRes>;

  updateIssue(request: UpdateIssueReq): Observable<IssueRes>;

  deleteIssue(request: DeleteIssueReq): Observable<Empty>;

  listIssues(request: ListIssuesReq): Observable<ListIssuesRes>;

  getActivities(request: GetActivitiesReq): Observable<GetActivitiesRes>;
}

export interface IssueServiceController {
  createIssue(request: CreateIssueReq): Promise<CreateIssueRes> | Observable<CreateIssueRes> | CreateIssueRes;

  getIssue(request: GetIssueReq): Promise<IssueRes> | Observable<IssueRes> | IssueRes;

  updateIssue(request: UpdateIssueReq): Promise<IssueRes> | Observable<IssueRes> | IssueRes;

  deleteIssue(request: DeleteIssueReq): void;

  listIssues(request: ListIssuesReq): Promise<ListIssuesRes> | Observable<ListIssuesRes> | ListIssuesRes;

  getActivities(request: GetActivitiesReq): Promise<GetActivitiesRes> | Observable<GetActivitiesRes> | GetActivitiesRes;
}

export function IssueServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "createIssue",
      "getIssue",
      "updateIssue",
      "deleteIssue",
      "listIssues",
      "getActivities",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("IssueService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("IssueService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const ISSUE_SERVICE_NAME = "IssueService";
