// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v3.21.12
// source: main_service/metadata.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "project_service";

export interface CreatePresignedURLImageReq {
  projectId: string;
  userId: string;
  fileName: string;
  contentType: string;
}

export interface CreatePresignedtURLImageRes {
  url: string;
}

export const PROJECT_SERVICE_PACKAGE_NAME = "project_service";

export interface MetadataServiceClient {
  createPresignedtUrlImage(request: CreatePresignedURLImageReq): Observable<CreatePresignedtURLImageRes>;
}

export interface MetadataServiceController {
  createPresignedtUrlImage(
    request: CreatePresignedURLImageReq,
  ): Promise<CreatePresignedtURLImageRes> | Observable<CreatePresignedtURLImageRes> | CreatePresignedtURLImageRes;
}

export function MetadataServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["createPresignedtUrlImage"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("MetadataService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("MetadataService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const METADATA_SERVICE_NAME = "MetadataService";
