// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v3.21.12
// source: main_service/project_team.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";
import { PaginationRes, ProjectTeamRes } from "../base";

export const protobufPackage = "project_service";

/** Permission */
export interface Permission {
  id: string;
  key: string;
  resource: string;
  action: string;
  label: string;
  description: string;
}

export interface CreateProjectTeamReq {
  projectId: string;
  name: string;
  description: string;
  memberIds: string[];
}

export interface CreateProjectTeamRes {
  status: string;
  message: string;
  data: ProjectTeamRes | undefined;
  pagination: PaginationRes | undefined;
}

export interface ListProjectTeamsReq {
  projectId: string;
  page: number;
  limit: number;
}

export interface ListProjectTeamsRes {
  status: string;
  message: string;
  data: ProjectTeamRes[];
  pagination: PaginationRes | undefined;
}

export interface GetProjectTeamReq {
  projectId: string;
  teamId: string;
}

export interface UpdateProjectTeamReq {
  projectId: string;
  teamId: string;
  name: string;
  description: string;
  permissionKeys: string[];
}

export interface UpdateProjectTeamRes {
  status: string;
  message: string;
  data: ProjectTeamRes | undefined;
  pagination: PaginationRes | undefined;
}

export interface GetProjectPermissionReq {
}

export interface GetProjectPermissionRes {
  permissions: Permission[];
}

export interface GetUserTeamsReq {
  projectId: string;
  userId: string;
}

export interface GetUserTeamsRes {
  data: ProjectTeamRes[];
}

export const PROJECT_SERVICE_PACKAGE_NAME = "project_service";

export interface ProjectTeamServiceClient {
  createProjectTeam(request: CreateProjectTeamReq): Observable<CreateProjectTeamRes>;

  listProjectTeams(request: ListProjectTeamsReq): Observable<ListProjectTeamsRes>;

  getProjectTeam(request: GetProjectTeamReq): Observable<ProjectTeamRes>;

  updateProjectTeam(request: UpdateProjectTeamReq): Observable<UpdateProjectTeamRes>;

  getUserTeams(request: GetUserTeamsReq): Observable<GetUserTeamsRes>;

  getProjectPermissions(request: GetProjectPermissionReq): Observable<GetProjectPermissionRes>;
}

export interface ProjectTeamServiceController {
  createProjectTeam(
    request: CreateProjectTeamReq,
  ): Promise<CreateProjectTeamRes> | Observable<CreateProjectTeamRes> | CreateProjectTeamRes;

  listProjectTeams(
    request: ListProjectTeamsReq,
  ): Promise<ListProjectTeamsRes> | Observable<ListProjectTeamsRes> | ListProjectTeamsRes;

  getProjectTeam(request: GetProjectTeamReq): Promise<ProjectTeamRes> | Observable<ProjectTeamRes> | ProjectTeamRes;

  updateProjectTeam(
    request: UpdateProjectTeamReq,
  ): Promise<UpdateProjectTeamRes> | Observable<UpdateProjectTeamRes> | UpdateProjectTeamRes;

  getUserTeams(request: GetUserTeamsReq): Promise<GetUserTeamsRes> | Observable<GetUserTeamsRes> | GetUserTeamsRes;

  getProjectPermissions(
    request: GetProjectPermissionReq,
  ): Promise<GetProjectPermissionRes> | Observable<GetProjectPermissionRes> | GetProjectPermissionRes;
}

export function ProjectTeamServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "createProjectTeam",
      "listProjectTeams",
      "getProjectTeam",
      "updateProjectTeam",
      "getUserTeams",
      "getProjectPermissions",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("ProjectTeamService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("ProjectTeamService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const PROJECT_TEAM_SERVICE_NAME = "ProjectTeamService";
