// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v3.21.12
// source: main_service/project.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";
import { ColumnRes, PaginationRes } from "../base";
import { Empty } from "../google/protobuf/empty";
import { ProjectMemberRes } from "./project_member";

export const protobufPackage = "project_service";

/** Define request message */
export enum ProjectAccess {
  Public = 0,
  Private = 1,
  Teams = 2,
  UNRECOGNIZED = -1,
}

export enum ProjectType {
  Scrum = 0,
  Kanban = 1,
  UNRECOGNIZED = -1,
}

export interface CreateProjectReq {
  name: string;
  key: string;
  access: ProjectAccess;
  type: ProjectType;
  ownerId: string;
}

export interface GetProjectReq {
  id: string;
}

export interface UpdateProjectReq {
  id: string;
  name: string;
  key: string;
  access: ProjectAccess;
  type: ProjectType;
  ownerId: string;
}

export interface DeleteProjectReq {
  id: string;
}

export interface ListProjectsReq {
  page: number;
  limit: number;
  kw: string;
  sort: string;
  projectIds: string[];
}

export interface UserProjectsReq {
  userId: string;
  page: number;
  limit: number;
  kw: string;
  sort: string;
}

export interface ProjectRes {
  id: string;
  name: string;
  key: string;
  access: ProjectAccess;
  type: ProjectType;
  ownerId: string;
  createdAt: string;
  updatedAt: string;
  projectMembers: ProjectMemberRes[];
}

export interface CreateProjectRes {
  status: string;
  message: string;
  data: ProjectRes | undefined;
  pagination?: PaginationRes | undefined;
}

export interface ListProjectsRes {
  status: string;
  message: string;
  data: ProjectRes[];
  pagination: PaginationRes | undefined;
}

export interface CreateColumnReq {
  projectId: string;
  name: string;
}

export interface CreateColumnRes {
  status: string;
  message: string;
  data: ColumnRes | undefined;
  pagination: PaginationRes | undefined;
}

export interface GetColumnsReq {
  projectId: string;
  dueDateFrom?: string | undefined;
  dueDateTo?: string | undefined;
  assigneeIds: string[];
  sprintIds: string[];
  types: string[];
  priorities: string[];
  title?: string | undefined;
  createdAtFrom?: string | undefined;
  createdAtTo?: string | undefined;
}

export interface GetColumnsRes {
  status: string;
  message: string;
  data: ColumnRes[];
  pagination: PaginationRes | undefined;
}

export interface ColumnOrder {
  id: string;
  order: number;
}

export interface UpdateColumnsOrderReq {
  projectId: string;
  columns: ColumnOrder[];
}

export interface UpdateColumnsOrderRes {
  status: string;
  message: string;
  data: ColumnRes[];
}

export interface UpdateColumnReq {
  name: string;
  columnId: string;
  projectId: string;
}

export interface UpdateColumnRes {
  status: string;
  message: string;
  data: ColumnRes | undefined;
  pagination: PaginationRes | undefined;
}

export interface DeleteColumnReq {
  columnId: string;
}

export interface DeleteColumnRes {
  message: string;
  status: string;
}

export const PROJECT_SERVICE_PACKAGE_NAME = "project_service";

/** Define the gRPC service */

export interface ProjectServiceClient {
  createProject(request: CreateProjectReq): Observable<CreateProjectRes>;

  getProject(request: GetProjectReq): Observable<ProjectRes>;

  updateProject(request: UpdateProjectReq): Observable<ProjectRes>;

  deleteProject(request: DeleteProjectReq): Observable<Empty>;

  listProjects(request: ListProjectsReq): Observable<ListProjectsRes>;

  getUserProjects(request: UserProjectsReq): Observable<ListProjectsRes>;

  createProjectColumn(request: CreateColumnReq): Observable<CreateColumnRes>;

  getProjectColumns(request: GetColumnsReq): Observable<GetColumnsRes>;

  updateOrderProjectColumns(request: UpdateColumnsOrderReq): Observable<UpdateColumnsOrderRes>;

  updateColumnProject(request: UpdateColumnReq): Observable<UpdateColumnRes>;

  deleteColumn(request: DeleteColumnReq): Observable<DeleteColumnRes>;
}

/** Define the gRPC service */

export interface ProjectServiceController {
  createProject(request: CreateProjectReq): Promise<CreateProjectRes> | Observable<CreateProjectRes> | CreateProjectRes;

  getProject(request: GetProjectReq): Promise<ProjectRes> | Observable<ProjectRes> | ProjectRes;

  updateProject(request: UpdateProjectReq): Promise<ProjectRes> | Observable<ProjectRes> | ProjectRes;

  deleteProject(request: DeleteProjectReq): void;

  listProjects(request: ListProjectsReq): Promise<ListProjectsRes> | Observable<ListProjectsRes> | ListProjectsRes;

  getUserProjects(request: UserProjectsReq): Promise<ListProjectsRes> | Observable<ListProjectsRes> | ListProjectsRes;

  createProjectColumn(
    request: CreateColumnReq,
  ): Promise<CreateColumnRes> | Observable<CreateColumnRes> | CreateColumnRes;

  getProjectColumns(request: GetColumnsReq): Promise<GetColumnsRes> | Observable<GetColumnsRes> | GetColumnsRes;

  updateOrderProjectColumns(
    request: UpdateColumnsOrderReq,
  ): Promise<UpdateColumnsOrderRes> | Observable<UpdateColumnsOrderRes> | UpdateColumnsOrderRes;

  updateColumnProject(
    request: UpdateColumnReq,
  ): Promise<UpdateColumnRes> | Observable<UpdateColumnRes> | UpdateColumnRes;

  deleteColumn(request: DeleteColumnReq): Promise<DeleteColumnRes> | Observable<DeleteColumnRes> | DeleteColumnRes;
}

export function ProjectServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "createProject",
      "getProject",
      "updateProject",
      "deleteProject",
      "listProjects",
      "getUserProjects",
      "createProjectColumn",
      "getProjectColumns",
      "updateOrderProjectColumns",
      "updateColumnProject",
      "deleteColumn",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("ProjectService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("ProjectService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const PROJECT_SERVICE_NAME = "ProjectService";
