// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v3.21.12
// source: main_service/project_member.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";
import { PaginationRes } from "../base";
import { Empty } from "../google/protobuf/empty";

export const protobufPackage = "project_service";

export enum ProjectMemberRole {
  MEMBER = 0,
  ADMIN = 1,
  OWNER = 2,
  VIEWER = 3,
  UNRECOGNIZED = -1,
}

export interface AddProjectMemberReq {
  projectId: string;
  userId: string;
  role: ProjectMemberRole;
}

export interface RemoveProjectMemberReq {
  projectId: string;
  userId: string;
}

export interface UpdateProjectMemberRoleReq {
  projectId: string;
  userId: string;
  role: ProjectMemberRole;
}

export interface ListProjectMembersReq {
  projectId: string;
  name?: string | undefined;
  email?: string | undefined;
  page: number;
  limit: number;
}

export interface ProjectMemberRes {
  id: string;
  projectId: string;
  userId: string;
  role: ProjectMemberRole;
  isPending: boolean;
  createdAt: string;
  updatedAt: string;
  user: UserInfo | undefined;
}

export interface UserInfo {
  id: string;
  firstName: string;
  lastName: string;
  email: string;
  avatar: string;
}

export interface ProjectInfo {
  id: string;
  name: string;
  description: string;
  status: string;
  createdAt: string;
  updatedAt: string;
  issuesCount?: number | undefined;
  membersCount?: number | undefined;
  dueDateFrom?: string | undefined;
  dueDateTo?: string | undefined;
  backgroundImg?: string | undefined;
}

export interface UserMembershipRes {
  id: string;
  projectId: string;
  userId: string;
  role: ProjectMemberRole;
  isPending: boolean;
  createdAt: string;
  updatedAt: string;
  project: ProjectInfo | undefined;
}

export interface ListProjectMembersRes {
  data: ProjectMemberRes[];
  pagination: PaginationRes | undefined;
}

export interface UserMembershipsReq {
  userId: string;
  page: number;
  limit: number;
}

export interface GetUserMembershipsRes {
  data: UserMembershipRes[];
  pagination: PaginationRes | undefined;
}

export interface ApproveMemberReq {
  projectId: string;
  userId: string;
}

export interface RejectMemberReq {
  projectId: string;
  userId: string;
}

export interface AcceptInvitationReq {
  projectId: string;
}

export interface RejectInvitationReq {
  projectId: string;
}

export interface AddMemberToTeamReq {
  projectId: string;
  teamId: string;
  userIds: string[];
}

export const PROJECT_SERVICE_PACKAGE_NAME = "project_service";

export interface ProjectMemberServiceClient {
  addProjectMember(request: AddProjectMemberReq): Observable<ProjectMemberRes>;

  removeProjectMember(request: RemoveProjectMemberReq): Observable<Empty>;

  updateProjectMemberRole(request: UpdateProjectMemberRoleReq): Observable<ProjectMemberRes>;

  listProjectMembers(request: ListProjectMembersReq): Observable<ListProjectMembersRes>;

  getUserMemberships(request: UserMembershipsReq): Observable<GetUserMembershipsRes>;

  approveMember(request: ApproveMemberReq): Observable<ProjectMemberRes>;

  rejectMember(request: RejectMemberReq): Observable<Empty>;

  acceptInvitation(request: AcceptInvitationReq): Observable<ProjectMemberRes>;

  rejectInvitation(request: RejectInvitationReq): Observable<Empty>;

  addMemberToTeam(request: AddMemberToTeamReq): Observable<Empty>;
}

export interface ProjectMemberServiceController {
  addProjectMember(
    request: AddProjectMemberReq,
  ): Promise<ProjectMemberRes> | Observable<ProjectMemberRes> | ProjectMemberRes;

  removeProjectMember(request: RemoveProjectMemberReq): void | Promise<void>;

  updateProjectMemberRole(
    request: UpdateProjectMemberRoleReq,
  ): Promise<ProjectMemberRes> | Observable<ProjectMemberRes> | ProjectMemberRes;

  listProjectMembers(
    request: ListProjectMembersReq,
  ): Promise<ListProjectMembersRes> | Observable<ListProjectMembersRes> | ListProjectMembersRes;

  getUserMemberships(
    request: UserMembershipsReq,
  ): Promise<GetUserMembershipsRes> | Observable<GetUserMembershipsRes> | GetUserMembershipsRes;

  approveMember(request: ApproveMemberReq): Promise<ProjectMemberRes> | Observable<ProjectMemberRes> | ProjectMemberRes;

  rejectMember(request: RejectMemberReq): void | Promise<void>;

  acceptInvitation(
    request: AcceptInvitationReq,
  ): Promise<ProjectMemberRes> | Observable<ProjectMemberRes> | ProjectMemberRes;

  rejectInvitation(request: RejectInvitationReq): void | Promise<void>;

  addMemberToTeam(request: AddMemberToTeamReq): void | Promise<void>;
}

export function ProjectMemberServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "addProjectMember",
      "removeProjectMember",
      "updateProjectMemberRole",
      "listProjectMembers",
      "getUserMemberships",
      "approveMember",
      "rejectMember",
      "acceptInvitation",
      "rejectInvitation",
      "addMemberToTeam",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("ProjectMemberService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("ProjectMemberService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const PROJECT_MEMBER_SERVICE_NAME = "ProjectMemberService";
