// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package adapter

import (
	"github.com/vudinhan2525/TaskFlow-Server/services/go-service/internal/media-service/core/services"
	"github.com/vudinhan2525/TaskFlow-Server/services/go-service/internal/media-service/infras/repos"
)

// Injectors from wire.go:

func InitializeGRPCServer() (*GRPCServer, error) {
	mediaRepo := repos.NewMediaRepo()
	mediaService := services.NewMediaService(mediaRepo)
	grpcServer := NewGRPCServer(mediaService)
	return grpcServer, nil
}
