version: "3.8"
services:
  envoy:
    image: envoyproxy/envoy:v1.33.0
    container_name: envoy_proxy
    ports:
      - "8081:8081" # HTTP (REST to gRPC)
      - "9901:9901" # Admin Panel
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
      - ./proto.pb:/etc/envoy/proto.pb
    networks:
      - taskflow-network
    depends_on:
      - grpc-server
  grpc-server:
    build:
      context: ./services/main-service # Path to your .NET project
      dockerfile: Dockerfile
    container_name: grpc_server
    ports:
      - "5001:5001" # Map host port 5001 to container port 5001
    networks:
      - taskflow-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:5001
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 10s
      timeout: 5s
      retries: 3
  kafka:
    image: bitnami/kafka:3.8
    container_name: kafka
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_BROKER_ID=1
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - kafka-data:/bitnami/kafka
    networks:
      - taskflow-network
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka_ui
    ports:
      - "8888:8888"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - SERVER_PORT=8888
    networks:
      - taskflow-network
  kafka-init:
    image: bitnami/kafka:3.8
    depends_on:
      - kafka
    entrypoint: ["/bin/sh", "-c"]
    command: >
      "
      echo '⏳ Waiting for Kafka to be ready...' &&
      sleep 10 &&
      kafka-topics.sh --create --if-not-exists --bootstrap-server kafka:9092 --topic notifications --partitions 1 --replication-factor 1 &&
      kafka-topics.sh --create --if-not-exists --bootstrap-server kafka:9092 --topic activities --partitions 1 --replication-factor 1 &&
      echo '✅ Kafka topics created!'
      "
    networks:
      - taskflow-network
  # cassandra:
  #   image: cassandra:latest
  #   container_name: cassandra
  #   environment:
  #     - CASSANDRA_CLUSTER_NAME=my-cluster
  #     - CASSANDRA_BROADCAST_ADDRESS=127.0.0.1
  #     - CASSANDRA_LISTEN_ADDRESS=127.0.0.1
  #   volumes:
  #     - cassandra-data:/var/lib/cassandra
  #   network_mode: "host"
  # cassandra-init:
  #   image: cassandra:latest
  #   depends_on:
  #     - cassandra
  #   entrypoint: ["/bin/sh", "-c"]
  #   command: >
  #     "
  #     echo '⏳ Waiting for Cassandra to be available...' &&
  #     while ! cqlsh 127.0.0.1 -e 'describe keyspaces'; do sleep 2; done &&
  #     echo '✅ Cassandra is up!' &&
  #     cqlsh 127.0.0.1 -e \"
  #       CREATE KEYSPACE IF NOT EXISTS taskflow
  #       WITH replication = {'class': 'SimpleStrategy', 'replication_factor': 1};

  #       USE taskflow;

  #       CREATE TABLE IF NOT EXISTS notifications (
  #         id TEXT PRIMARY KEY,
  #       );
  #     \"
  #     "
  #   network_mode: "host"
networks:
  taskflow-network:
    driver: bridge
volumes:
  esdata: {}
  kong-data: {}
  kafka-data: {}
  cassandra-data: {}
