// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: main_service/project.proto

package main_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProjectService_CreateProject_FullMethodName             = "/project_service.ProjectService/CreateProject"
	ProjectService_GetProject_FullMethodName                = "/project_service.ProjectService/GetProject"
	ProjectService_UpdateProject_FullMethodName             = "/project_service.ProjectService/UpdateProject"
	ProjectService_DeleteProject_FullMethodName             = "/project_service.ProjectService/DeleteProject"
	ProjectService_ListProjects_FullMethodName              = "/project_service.ProjectService/ListProjects"
	ProjectService_GetUserProjects_FullMethodName           = "/project_service.ProjectService/GetUserProjects"
	ProjectService_CreateProjectColumn_FullMethodName       = "/project_service.ProjectService/CreateProjectColumn"
	ProjectService_GetProjectColumns_FullMethodName         = "/project_service.ProjectService/GetProjectColumns"
	ProjectService_UpdateOrderProjectColumns_FullMethodName = "/project_service.ProjectService/UpdateOrderProjectColumns"
	ProjectService_UpdateColumnProject_FullMethodName       = "/project_service.ProjectService/UpdateColumnProject"
	ProjectService_DeleteColumn_FullMethodName              = "/project_service.ProjectService/DeleteColumn"
)

// ProjectServiceClient is the client API for ProjectService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Define the gRPC service
type ProjectServiceClient interface {
	CreateProject(ctx context.Context, in *CreateProjectReq, opts ...grpc.CallOption) (*CreateProjectRes, error)
	GetProject(ctx context.Context, in *GetProjectReq, opts ...grpc.CallOption) (*ProjectRes, error)
	UpdateProject(ctx context.Context, in *UpdateProjectReq, opts ...grpc.CallOption) (*ProjectRes, error)
	DeleteProject(ctx context.Context, in *DeleteProjectReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ListProjects(ctx context.Context, in *ListProjectsReq, opts ...grpc.CallOption) (*ListProjectsRes, error)
	GetUserProjects(ctx context.Context, in *UserProjectsReq, opts ...grpc.CallOption) (*ListProjectsRes, error)
	CreateProjectColumn(ctx context.Context, in *CreateColumnReq, opts ...grpc.CallOption) (*CreateColumnRes, error)
	GetProjectColumns(ctx context.Context, in *GetColumnsReq, opts ...grpc.CallOption) (*GetColumnsRes, error)
	UpdateOrderProjectColumns(ctx context.Context, in *UpdateColumnsOrderReq, opts ...grpc.CallOption) (*UpdateColumnsOrderRes, error)
	UpdateColumnProject(ctx context.Context, in *UpdateColumnReq, opts ...grpc.CallOption) (*UpdateColumnRes, error)
	DeleteColumn(ctx context.Context, in *DeleteColumnReq, opts ...grpc.CallOption) (*DeleteColumnRes, error)
}

type projectServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProjectServiceClient(cc grpc.ClientConnInterface) ProjectServiceClient {
	return &projectServiceClient{cc}
}

func (c *projectServiceClient) CreateProject(ctx context.Context, in *CreateProjectReq, opts ...grpc.CallOption) (*CreateProjectRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateProjectRes)
	err := c.cc.Invoke(ctx, ProjectService_CreateProject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) GetProject(ctx context.Context, in *GetProjectReq, opts ...grpc.CallOption) (*ProjectRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProjectRes)
	err := c.cc.Invoke(ctx, ProjectService_GetProject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) UpdateProject(ctx context.Context, in *UpdateProjectReq, opts ...grpc.CallOption) (*ProjectRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProjectRes)
	err := c.cc.Invoke(ctx, ProjectService_UpdateProject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) DeleteProject(ctx context.Context, in *DeleteProjectReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ProjectService_DeleteProject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) ListProjects(ctx context.Context, in *ListProjectsReq, opts ...grpc.CallOption) (*ListProjectsRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListProjectsRes)
	err := c.cc.Invoke(ctx, ProjectService_ListProjects_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) GetUserProjects(ctx context.Context, in *UserProjectsReq, opts ...grpc.CallOption) (*ListProjectsRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListProjectsRes)
	err := c.cc.Invoke(ctx, ProjectService_GetUserProjects_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) CreateProjectColumn(ctx context.Context, in *CreateColumnReq, opts ...grpc.CallOption) (*CreateColumnRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateColumnRes)
	err := c.cc.Invoke(ctx, ProjectService_CreateProjectColumn_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) GetProjectColumns(ctx context.Context, in *GetColumnsReq, opts ...grpc.CallOption) (*GetColumnsRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetColumnsRes)
	err := c.cc.Invoke(ctx, ProjectService_GetProjectColumns_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) UpdateOrderProjectColumns(ctx context.Context, in *UpdateColumnsOrderReq, opts ...grpc.CallOption) (*UpdateColumnsOrderRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateColumnsOrderRes)
	err := c.cc.Invoke(ctx, ProjectService_UpdateOrderProjectColumns_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) UpdateColumnProject(ctx context.Context, in *UpdateColumnReq, opts ...grpc.CallOption) (*UpdateColumnRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateColumnRes)
	err := c.cc.Invoke(ctx, ProjectService_UpdateColumnProject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) DeleteColumn(ctx context.Context, in *DeleteColumnReq, opts ...grpc.CallOption) (*DeleteColumnRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteColumnRes)
	err := c.cc.Invoke(ctx, ProjectService_DeleteColumn_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProjectServiceServer is the server API for ProjectService service.
// All implementations must embed UnimplementedProjectServiceServer
// for forward compatibility.
//
// Define the gRPC service
type ProjectServiceServer interface {
	CreateProject(context.Context, *CreateProjectReq) (*CreateProjectRes, error)
	GetProject(context.Context, *GetProjectReq) (*ProjectRes, error)
	UpdateProject(context.Context, *UpdateProjectReq) (*ProjectRes, error)
	DeleteProject(context.Context, *DeleteProjectReq) (*emptypb.Empty, error)
	ListProjects(context.Context, *ListProjectsReq) (*ListProjectsRes, error)
	GetUserProjects(context.Context, *UserProjectsReq) (*ListProjectsRes, error)
	CreateProjectColumn(context.Context, *CreateColumnReq) (*CreateColumnRes, error)
	GetProjectColumns(context.Context, *GetColumnsReq) (*GetColumnsRes, error)
	UpdateOrderProjectColumns(context.Context, *UpdateColumnsOrderReq) (*UpdateColumnsOrderRes, error)
	UpdateColumnProject(context.Context, *UpdateColumnReq) (*UpdateColumnRes, error)
	DeleteColumn(context.Context, *DeleteColumnReq) (*DeleteColumnRes, error)
	mustEmbedUnimplementedProjectServiceServer()
}

// UnimplementedProjectServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProjectServiceServer struct{}

func (UnimplementedProjectServiceServer) CreateProject(context.Context, *CreateProjectReq) (*CreateProjectRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateProject not implemented")
}
func (UnimplementedProjectServiceServer) GetProject(context.Context, *GetProjectReq) (*ProjectRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProject not implemented")
}
func (UnimplementedProjectServiceServer) UpdateProject(context.Context, *UpdateProjectReq) (*ProjectRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateProject not implemented")
}
func (UnimplementedProjectServiceServer) DeleteProject(context.Context, *DeleteProjectReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteProject not implemented")
}
func (UnimplementedProjectServiceServer) ListProjects(context.Context, *ListProjectsReq) (*ListProjectsRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListProjects not implemented")
}
func (UnimplementedProjectServiceServer) GetUserProjects(context.Context, *UserProjectsReq) (*ListProjectsRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserProjects not implemented")
}
func (UnimplementedProjectServiceServer) CreateProjectColumn(context.Context, *CreateColumnReq) (*CreateColumnRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateProjectColumn not implemented")
}
func (UnimplementedProjectServiceServer) GetProjectColumns(context.Context, *GetColumnsReq) (*GetColumnsRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProjectColumns not implemented")
}
func (UnimplementedProjectServiceServer) UpdateOrderProjectColumns(context.Context, *UpdateColumnsOrderReq) (*UpdateColumnsOrderRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateOrderProjectColumns not implemented")
}
func (UnimplementedProjectServiceServer) UpdateColumnProject(context.Context, *UpdateColumnReq) (*UpdateColumnRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateColumnProject not implemented")
}
func (UnimplementedProjectServiceServer) DeleteColumn(context.Context, *DeleteColumnReq) (*DeleteColumnRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteColumn not implemented")
}
func (UnimplementedProjectServiceServer) mustEmbedUnimplementedProjectServiceServer() {}
func (UnimplementedProjectServiceServer) testEmbeddedByValue()                        {}

// UnsafeProjectServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProjectServiceServer will
// result in compilation errors.
type UnsafeProjectServiceServer interface {
	mustEmbedUnimplementedProjectServiceServer()
}

func RegisterProjectServiceServer(s grpc.ServiceRegistrar, srv ProjectServiceServer) {
	// If the following call pancis, it indicates UnimplementedProjectServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProjectService_ServiceDesc, srv)
}

func _ProjectService_CreateProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProjectReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).CreateProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_CreateProject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).CreateProject(ctx, req.(*CreateProjectReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_GetProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProjectReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).GetProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_GetProject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).GetProject(ctx, req.(*GetProjectReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_UpdateProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProjectReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).UpdateProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_UpdateProject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).UpdateProject(ctx, req.(*UpdateProjectReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_DeleteProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteProjectReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).DeleteProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_DeleteProject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).DeleteProject(ctx, req.(*DeleteProjectReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_ListProjects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProjectsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).ListProjects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_ListProjects_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).ListProjects(ctx, req.(*ListProjectsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_GetUserProjects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserProjectsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).GetUserProjects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_GetUserProjects_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).GetUserProjects(ctx, req.(*UserProjectsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_CreateProjectColumn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateColumnReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).CreateProjectColumn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_CreateProjectColumn_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).CreateProjectColumn(ctx, req.(*CreateColumnReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_GetProjectColumns_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetColumnsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).GetProjectColumns(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_GetProjectColumns_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).GetProjectColumns(ctx, req.(*GetColumnsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_UpdateOrderProjectColumns_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateColumnsOrderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).UpdateOrderProjectColumns(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_UpdateOrderProjectColumns_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).UpdateOrderProjectColumns(ctx, req.(*UpdateColumnsOrderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_UpdateColumnProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateColumnReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).UpdateColumnProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_UpdateColumnProject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).UpdateColumnProject(ctx, req.(*UpdateColumnReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_DeleteColumn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteColumnReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).DeleteColumn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_DeleteColumn_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).DeleteColumn(ctx, req.(*DeleteColumnReq))
	}
	return interceptor(ctx, in, info, handler)
}

// ProjectService_ServiceDesc is the grpc.ServiceDesc for ProjectService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProjectService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "project_service.ProjectService",
	HandlerType: (*ProjectServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateProject",
			Handler:    _ProjectService_CreateProject_Handler,
		},
		{
			MethodName: "GetProject",
			Handler:    _ProjectService_GetProject_Handler,
		},
		{
			MethodName: "UpdateProject",
			Handler:    _ProjectService_UpdateProject_Handler,
		},
		{
			MethodName: "DeleteProject",
			Handler:    _ProjectService_DeleteProject_Handler,
		},
		{
			MethodName: "ListProjects",
			Handler:    _ProjectService_ListProjects_Handler,
		},
		{
			MethodName: "GetUserProjects",
			Handler:    _ProjectService_GetUserProjects_Handler,
		},
		{
			MethodName: "CreateProjectColumn",
			Handler:    _ProjectService_CreateProjectColumn_Handler,
		},
		{
			MethodName: "GetProjectColumns",
			Handler:    _ProjectService_GetProjectColumns_Handler,
		},
		{
			MethodName: "UpdateOrderProjectColumns",
			Handler:    _ProjectService_UpdateOrderProjectColumns_Handler,
		},
		{
			MethodName: "UpdateColumnProject",
			Handler:    _ProjectService_UpdateColumnProject_Handler,
		},
		{
			MethodName: "DeleteColumn",
			Handler:    _ProjectService_DeleteColumn_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "main_service/project.proto",
}
