// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: main_service/project_member.proto

package main_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProjectMemberService_AddProjectMember_FullMethodName        = "/project_service.ProjectMemberService/AddProjectMember"
	ProjectMemberService_RemoveProjectMember_FullMethodName     = "/project_service.ProjectMemberService/RemoveProjectMember"
	ProjectMemberService_UpdateProjectMemberRole_FullMethodName = "/project_service.ProjectMemberService/UpdateProjectMemberRole"
	ProjectMemberService_ListProjectMembers_FullMethodName      = "/project_service.ProjectMemberService/ListProjectMembers"
	ProjectMemberService_GetUserMemberships_FullMethodName      = "/project_service.ProjectMemberService/GetUserMemberships"
	ProjectMemberService_ApproveMember_FullMethodName           = "/project_service.ProjectMemberService/ApproveMember"
	ProjectMemberService_RejectMember_FullMethodName            = "/project_service.ProjectMemberService/RejectMember"
	ProjectMemberService_AcceptInvitation_FullMethodName        = "/project_service.ProjectMemberService/AcceptInvitation"
	ProjectMemberService_RejectInvitation_FullMethodName        = "/project_service.ProjectMemberService/RejectInvitation"
)

// ProjectMemberServiceClient is the client API for ProjectMemberService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProjectMemberServiceClient interface {
	AddProjectMember(ctx context.Context, in *AddProjectMemberReq, opts ...grpc.CallOption) (*ProjectMemberRes, error)
	RemoveProjectMember(ctx context.Context, in *RemoveProjectMemberReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	UpdateProjectMemberRole(ctx context.Context, in *UpdateProjectMemberRoleReq, opts ...grpc.CallOption) (*ProjectMemberRes, error)
	ListProjectMembers(ctx context.Context, in *ListProjectMembersReq, opts ...grpc.CallOption) (*ListProjectMembersRes, error)
	GetUserMemberships(ctx context.Context, in *UserMembershipsReq, opts ...grpc.CallOption) (*GetUserMembershipsRes, error)
	ApproveMember(ctx context.Context, in *ApproveMemberReq, opts ...grpc.CallOption) (*ProjectMemberRes, error)
	RejectMember(ctx context.Context, in *RejectMemberReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	AcceptInvitation(ctx context.Context, in *AcceptInvitationReq, opts ...grpc.CallOption) (*ProjectMemberRes, error)
	RejectInvitation(ctx context.Context, in *RejectInvitationReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type projectMemberServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProjectMemberServiceClient(cc grpc.ClientConnInterface) ProjectMemberServiceClient {
	return &projectMemberServiceClient{cc}
}

func (c *projectMemberServiceClient) AddProjectMember(ctx context.Context, in *AddProjectMemberReq, opts ...grpc.CallOption) (*ProjectMemberRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProjectMemberRes)
	err := c.cc.Invoke(ctx, ProjectMemberService_AddProjectMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectMemberServiceClient) RemoveProjectMember(ctx context.Context, in *RemoveProjectMemberReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ProjectMemberService_RemoveProjectMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectMemberServiceClient) UpdateProjectMemberRole(ctx context.Context, in *UpdateProjectMemberRoleReq, opts ...grpc.CallOption) (*ProjectMemberRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProjectMemberRes)
	err := c.cc.Invoke(ctx, ProjectMemberService_UpdateProjectMemberRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectMemberServiceClient) ListProjectMembers(ctx context.Context, in *ListProjectMembersReq, opts ...grpc.CallOption) (*ListProjectMembersRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListProjectMembersRes)
	err := c.cc.Invoke(ctx, ProjectMemberService_ListProjectMembers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectMemberServiceClient) GetUserMemberships(ctx context.Context, in *UserMembershipsReq, opts ...grpc.CallOption) (*GetUserMembershipsRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserMembershipsRes)
	err := c.cc.Invoke(ctx, ProjectMemberService_GetUserMemberships_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectMemberServiceClient) ApproveMember(ctx context.Context, in *ApproveMemberReq, opts ...grpc.CallOption) (*ProjectMemberRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProjectMemberRes)
	err := c.cc.Invoke(ctx, ProjectMemberService_ApproveMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectMemberServiceClient) RejectMember(ctx context.Context, in *RejectMemberReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ProjectMemberService_RejectMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectMemberServiceClient) AcceptInvitation(ctx context.Context, in *AcceptInvitationReq, opts ...grpc.CallOption) (*ProjectMemberRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProjectMemberRes)
	err := c.cc.Invoke(ctx, ProjectMemberService_AcceptInvitation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectMemberServiceClient) RejectInvitation(ctx context.Context, in *RejectInvitationReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ProjectMemberService_RejectInvitation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProjectMemberServiceServer is the server API for ProjectMemberService service.
// All implementations must embed UnimplementedProjectMemberServiceServer
// for forward compatibility.
type ProjectMemberServiceServer interface {
	AddProjectMember(context.Context, *AddProjectMemberReq) (*ProjectMemberRes, error)
	RemoveProjectMember(context.Context, *RemoveProjectMemberReq) (*emptypb.Empty, error)
	UpdateProjectMemberRole(context.Context, *UpdateProjectMemberRoleReq) (*ProjectMemberRes, error)
	ListProjectMembers(context.Context, *ListProjectMembersReq) (*ListProjectMembersRes, error)
	GetUserMemberships(context.Context, *UserMembershipsReq) (*GetUserMembershipsRes, error)
	ApproveMember(context.Context, *ApproveMemberReq) (*ProjectMemberRes, error)
	RejectMember(context.Context, *RejectMemberReq) (*emptypb.Empty, error)
	AcceptInvitation(context.Context, *AcceptInvitationReq) (*ProjectMemberRes, error)
	RejectInvitation(context.Context, *RejectInvitationReq) (*emptypb.Empty, error)
	mustEmbedUnimplementedProjectMemberServiceServer()
}

// UnimplementedProjectMemberServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProjectMemberServiceServer struct{}

func (UnimplementedProjectMemberServiceServer) AddProjectMember(context.Context, *AddProjectMemberReq) (*ProjectMemberRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddProjectMember not implemented")
}
func (UnimplementedProjectMemberServiceServer) RemoveProjectMember(context.Context, *RemoveProjectMemberReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveProjectMember not implemented")
}
func (UnimplementedProjectMemberServiceServer) UpdateProjectMemberRole(context.Context, *UpdateProjectMemberRoleReq) (*ProjectMemberRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateProjectMemberRole not implemented")
}
func (UnimplementedProjectMemberServiceServer) ListProjectMembers(context.Context, *ListProjectMembersReq) (*ListProjectMembersRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListProjectMembers not implemented")
}
func (UnimplementedProjectMemberServiceServer) GetUserMemberships(context.Context, *UserMembershipsReq) (*GetUserMembershipsRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserMemberships not implemented")
}
func (UnimplementedProjectMemberServiceServer) ApproveMember(context.Context, *ApproveMemberReq) (*ProjectMemberRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApproveMember not implemented")
}
func (UnimplementedProjectMemberServiceServer) RejectMember(context.Context, *RejectMemberReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RejectMember not implemented")
}
func (UnimplementedProjectMemberServiceServer) AcceptInvitation(context.Context, *AcceptInvitationReq) (*ProjectMemberRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AcceptInvitation not implemented")
}
func (UnimplementedProjectMemberServiceServer) RejectInvitation(context.Context, *RejectInvitationReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RejectInvitation not implemented")
}
func (UnimplementedProjectMemberServiceServer) mustEmbedUnimplementedProjectMemberServiceServer() {}
func (UnimplementedProjectMemberServiceServer) testEmbeddedByValue()                              {}

// UnsafeProjectMemberServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProjectMemberServiceServer will
// result in compilation errors.
type UnsafeProjectMemberServiceServer interface {
	mustEmbedUnimplementedProjectMemberServiceServer()
}

func RegisterProjectMemberServiceServer(s grpc.ServiceRegistrar, srv ProjectMemberServiceServer) {
	// If the following call pancis, it indicates UnimplementedProjectMemberServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProjectMemberService_ServiceDesc, srv)
}

func _ProjectMemberService_AddProjectMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddProjectMemberReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectMemberServiceServer).AddProjectMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectMemberService_AddProjectMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectMemberServiceServer).AddProjectMember(ctx, req.(*AddProjectMemberReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectMemberService_RemoveProjectMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveProjectMemberReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectMemberServiceServer).RemoveProjectMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectMemberService_RemoveProjectMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectMemberServiceServer).RemoveProjectMember(ctx, req.(*RemoveProjectMemberReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectMemberService_UpdateProjectMemberRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProjectMemberRoleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectMemberServiceServer).UpdateProjectMemberRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectMemberService_UpdateProjectMemberRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectMemberServiceServer).UpdateProjectMemberRole(ctx, req.(*UpdateProjectMemberRoleReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectMemberService_ListProjectMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProjectMembersReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectMemberServiceServer).ListProjectMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectMemberService_ListProjectMembers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectMemberServiceServer).ListProjectMembers(ctx, req.(*ListProjectMembersReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectMemberService_GetUserMemberships_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserMembershipsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectMemberServiceServer).GetUserMemberships(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectMemberService_GetUserMemberships_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectMemberServiceServer).GetUserMemberships(ctx, req.(*UserMembershipsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectMemberService_ApproveMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApproveMemberReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectMemberServiceServer).ApproveMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectMemberService_ApproveMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectMemberServiceServer).ApproveMember(ctx, req.(*ApproveMemberReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectMemberService_RejectMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RejectMemberReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectMemberServiceServer).RejectMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectMemberService_RejectMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectMemberServiceServer).RejectMember(ctx, req.(*RejectMemberReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectMemberService_AcceptInvitation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcceptInvitationReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectMemberServiceServer).AcceptInvitation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectMemberService_AcceptInvitation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectMemberServiceServer).AcceptInvitation(ctx, req.(*AcceptInvitationReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectMemberService_RejectInvitation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RejectInvitationReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectMemberServiceServer).RejectInvitation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectMemberService_RejectInvitation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectMemberServiceServer).RejectInvitation(ctx, req.(*RejectInvitationReq))
	}
	return interceptor(ctx, in, info, handler)
}

// ProjectMemberService_ServiceDesc is the grpc.ServiceDesc for ProjectMemberService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProjectMemberService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "project_service.ProjectMemberService",
	HandlerType: (*ProjectMemberServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddProjectMember",
			Handler:    _ProjectMemberService_AddProjectMember_Handler,
		},
		{
			MethodName: "RemoveProjectMember",
			Handler:    _ProjectMemberService_RemoveProjectMember_Handler,
		},
		{
			MethodName: "UpdateProjectMemberRole",
			Handler:    _ProjectMemberService_UpdateProjectMemberRole_Handler,
		},
		{
			MethodName: "ListProjectMembers",
			Handler:    _ProjectMemberService_ListProjectMembers_Handler,
		},
		{
			MethodName: "GetUserMemberships",
			Handler:    _ProjectMemberService_GetUserMemberships_Handler,
		},
		{
			MethodName: "ApproveMember",
			Handler:    _ProjectMemberService_ApproveMember_Handler,
		},
		{
			MethodName: "RejectMember",
			Handler:    _ProjectMemberService_RejectMember_Handler,
		},
		{
			MethodName: "AcceptInvitation",
			Handler:    _ProjectMemberService_AcceptInvitation_Handler,
		},
		{
			MethodName: "RejectInvitation",
			Handler:    _ProjectMemberService_RejectInvitation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "main_service/project_member.proto",
}
