// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: main_service/sprint.proto

package main_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SprintService_CreateSprint_FullMethodName   = "/project_service.SprintService/CreateSprint"
	SprintService_GetSprint_FullMethodName      = "/project_service.SprintService/GetSprint"
	SprintService_UpdateSprint_FullMethodName   = "/project_service.SprintService/UpdateSprint"
	SprintService_DeleteSprint_FullMethodName   = "/project_service.SprintService/DeleteSprint"
	SprintService_ListSprints_FullMethodName    = "/project_service.SprintService/ListSprints"
	SprintService_GetSprintStats_FullMethodName = "/project_service.SprintService/GetSprintStats"
)

// SprintServiceClient is the client API for SprintService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SprintServiceClient interface {
	CreateSprint(ctx context.Context, in *CreateSprintReq, opts ...grpc.CallOption) (*CreateSprintRes, error)
	GetSprint(ctx context.Context, in *GetSprintReq, opts ...grpc.CallOption) (*SprintRes, error)
	UpdateSprint(ctx context.Context, in *UpdateSprintReq, opts ...grpc.CallOption) (*SprintRes, error)
	DeleteSprint(ctx context.Context, in *DeleteSprintReq, opts ...grpc.CallOption) (*Empty, error)
	ListSprints(ctx context.Context, in *ListSprintsReq, opts ...grpc.CallOption) (*ListSprintsRes, error)
	GetSprintStats(ctx context.Context, in *GetSrintStatsReq, opts ...grpc.CallOption) (*GetSrintStatsRes, error)
}

type sprintServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSprintServiceClient(cc grpc.ClientConnInterface) SprintServiceClient {
	return &sprintServiceClient{cc}
}

func (c *sprintServiceClient) CreateSprint(ctx context.Context, in *CreateSprintReq, opts ...grpc.CallOption) (*CreateSprintRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSprintRes)
	err := c.cc.Invoke(ctx, SprintService_CreateSprint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sprintServiceClient) GetSprint(ctx context.Context, in *GetSprintReq, opts ...grpc.CallOption) (*SprintRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SprintRes)
	err := c.cc.Invoke(ctx, SprintService_GetSprint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sprintServiceClient) UpdateSprint(ctx context.Context, in *UpdateSprintReq, opts ...grpc.CallOption) (*SprintRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SprintRes)
	err := c.cc.Invoke(ctx, SprintService_UpdateSprint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sprintServiceClient) DeleteSprint(ctx context.Context, in *DeleteSprintReq, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, SprintService_DeleteSprint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sprintServiceClient) ListSprints(ctx context.Context, in *ListSprintsReq, opts ...grpc.CallOption) (*ListSprintsRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSprintsRes)
	err := c.cc.Invoke(ctx, SprintService_ListSprints_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sprintServiceClient) GetSprintStats(ctx context.Context, in *GetSrintStatsReq, opts ...grpc.CallOption) (*GetSrintStatsRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSrintStatsRes)
	err := c.cc.Invoke(ctx, SprintService_GetSprintStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SprintServiceServer is the server API for SprintService service.
// All implementations must embed UnimplementedSprintServiceServer
// for forward compatibility.
type SprintServiceServer interface {
	CreateSprint(context.Context, *CreateSprintReq) (*CreateSprintRes, error)
	GetSprint(context.Context, *GetSprintReq) (*SprintRes, error)
	UpdateSprint(context.Context, *UpdateSprintReq) (*SprintRes, error)
	DeleteSprint(context.Context, *DeleteSprintReq) (*Empty, error)
	ListSprints(context.Context, *ListSprintsReq) (*ListSprintsRes, error)
	GetSprintStats(context.Context, *GetSrintStatsReq) (*GetSrintStatsRes, error)
	mustEmbedUnimplementedSprintServiceServer()
}

// UnimplementedSprintServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSprintServiceServer struct{}

func (UnimplementedSprintServiceServer) CreateSprint(context.Context, *CreateSprintReq) (*CreateSprintRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSprint not implemented")
}
func (UnimplementedSprintServiceServer) GetSprint(context.Context, *GetSprintReq) (*SprintRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSprint not implemented")
}
func (UnimplementedSprintServiceServer) UpdateSprint(context.Context, *UpdateSprintReq) (*SprintRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSprint not implemented")
}
func (UnimplementedSprintServiceServer) DeleteSprint(context.Context, *DeleteSprintReq) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSprint not implemented")
}
func (UnimplementedSprintServiceServer) ListSprints(context.Context, *ListSprintsReq) (*ListSprintsRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSprints not implemented")
}
func (UnimplementedSprintServiceServer) GetSprintStats(context.Context, *GetSrintStatsReq) (*GetSrintStatsRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSprintStats not implemented")
}
func (UnimplementedSprintServiceServer) mustEmbedUnimplementedSprintServiceServer() {}
func (UnimplementedSprintServiceServer) testEmbeddedByValue()                       {}

// UnsafeSprintServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SprintServiceServer will
// result in compilation errors.
type UnsafeSprintServiceServer interface {
	mustEmbedUnimplementedSprintServiceServer()
}

func RegisterSprintServiceServer(s grpc.ServiceRegistrar, srv SprintServiceServer) {
	// If the following call pancis, it indicates UnimplementedSprintServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SprintService_ServiceDesc, srv)
}

func _SprintService_CreateSprint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSprintReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SprintServiceServer).CreateSprint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SprintService_CreateSprint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SprintServiceServer).CreateSprint(ctx, req.(*CreateSprintReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SprintService_GetSprint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSprintReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SprintServiceServer).GetSprint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SprintService_GetSprint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SprintServiceServer).GetSprint(ctx, req.(*GetSprintReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SprintService_UpdateSprint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSprintReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SprintServiceServer).UpdateSprint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SprintService_UpdateSprint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SprintServiceServer).UpdateSprint(ctx, req.(*UpdateSprintReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SprintService_DeleteSprint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSprintReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SprintServiceServer).DeleteSprint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SprintService_DeleteSprint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SprintServiceServer).DeleteSprint(ctx, req.(*DeleteSprintReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SprintService_ListSprints_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSprintsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SprintServiceServer).ListSprints(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SprintService_ListSprints_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SprintServiceServer).ListSprints(ctx, req.(*ListSprintsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SprintService_GetSprintStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSrintStatsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SprintServiceServer).GetSprintStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SprintService_GetSprintStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SprintServiceServer).GetSprintStats(ctx, req.(*GetSrintStatsReq))
	}
	return interceptor(ctx, in, info, handler)
}

// SprintService_ServiceDesc is the grpc.ServiceDesc for SprintService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SprintService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "project_service.SprintService",
	HandlerType: (*SprintServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSprint",
			Handler:    _SprintService_CreateSprint_Handler,
		},
		{
			MethodName: "GetSprint",
			Handler:    _SprintService_GetSprint_Handler,
		},
		{
			MethodName: "UpdateSprint",
			Handler:    _SprintService_UpdateSprint_Handler,
		},
		{
			MethodName: "DeleteSprint",
			Handler:    _SprintService_DeleteSprint_Handler,
		},
		{
			MethodName: "ListSprints",
			Handler:    _SprintService_ListSprints_Handler,
		},
		{
			MethodName: "GetSprintStats",
			Handler:    _SprintService_GetSprintStats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "main_service/sprint.proto",
}
