syntax = "proto3";

package notification_service;

import "google/api/annotations.proto";
import "base.proto";
option go_package = "github.com/vudinhan2525/TaskFlow-Server/services/go-service/types/noti_service;noti_service";

service NotificationService {
  rpc SendNotification (CreateNotificationReq) returns (CreateNotificationRes) {
    option (google.api.http) = {
      post: "/api/v1/notifications"
      body: "*"
    };
  }
  rpc GetAllNotifications (GetAllNotificationsReq) returns (GetAllNotificationsRes) {
    option (google.api.http) = {
      post: "/api/v1/notifications/get-all",
      body: "*"
    };
  }
}

message GetAllNotificationsReq {
  optional string user_id = 1;
  optional string project_id = 2;
  optional string sprint_id = 3;
  optional int32 page = 4;
  optional int32 limit = 5;
}

message GetAllNotificationsRes {
  string status = 1;
  string message = 2;
  base.PaginationRes pagination = 4;
  repeated NotificationRes data = 5;
}

message CreateNotificationReq {
  string recipient_id = 1;
  optional string actor_id = 2;
  string type = 3;
  optional string reference_id = 4;
  optional string reference_type = 5;
  optional string content = 6;
  bool is_read = 7;
}

message CreateNotificationRes {
  string status = 1;
  string message = 2;
  NotificationRes data = 3;
}

message NotificationRes {
  string recipient_id = 1;
  string actor_id = 2;
  string type = 3;
  string reference_id = 4;
  string reference_type = 5;
  string content = 6;
  bool is_read = 7;
  string created_at = 8;
}