syntax = "proto3";

option csharp_namespace = "TaskFlow.UserService";

package project_service;

import "google/api/annotations.proto";

// Define the gRPC service
service UserService {
  rpc CreateUser (CreateUserReq) returns (CreateUserRes) {
    option (google.api.http) = {
      post: "/api/v1/users"
      body: "*"
    };
  }
  rpc Login (LoginUserReq) returns (LoginUserRes) {
    option (google.api.http) = {
      post: "/api/v1/users/login"
      body: "*"
    };
  }
  rpc Register (RegisterUserReq) returns (CreateUserRes) {
    option (google.api.http) = {
      post: "/api/v1/users/register"
      body: "*"
    };
  }
  rpc UpdateUser (UpdateUserReq) returns (UpdateUserRes) {
    option (google.api.http) = {
      put: "/api/v1/users"
      body: "*"
    };
  }
  rpc GetById (GetUserReq) returns (GetUserRes) {
    option (google.api.http) = {
      get: "/api/v1/users/{user_id}"
    };
  }
  rpc GetMe (GetUserReq) returns (GetUserRes) {
    option (google.api.http) = {
      get: "/api/v1/users/get-me"
    };
  }

  rpc GetByEmail (GetUserByEmailReq) returns (GetUserRes) {
    option (google.api.http) = {
      get: "/api/v1/users/by-email/{email}"
    };
  }
  rpc ListUsers(ListUsersReq) returns (ListUsersRes){
    option (google.api.http) = {
      get: "/api/v1/users/list-users"
    };
  }
  rpc Logout (LogoutUserReq) returns (LogoutUserRes) {
    option (google.api.http) = {
      post: "/api/v1/users/logout"
      body: "*"
    };
  }
}

// LogoutUserReq and LogoutUserRes
message LogoutUserReq {
}

message LogoutUserRes {
  string status = 1;
  string message = 2;
}

// LOGIN
message LoginUserReq {
  string email = 1;
  string password = 2;
}

message LoginUserRes {
  string status = 1;
  string message = 2;
  UserRes data = 3;
}

// Get user by email
message GetUserByEmailReq {
  string email = 1;
}

// Get one user
message GetUserReq {
  string user_id = 1;
}

message GetUserRes {
  string status = 1;
  UserRes data = 2;
}
// List User
message ListUsersReq {
  optional string name = 1;
  optional string email = 2;
  int32 page = 3;
  int32 limit = 4;
}

message ListUsersRes{
  string status = 1;
  repeated UserRes data = 2;
  PaginationRes pagination = 3;
}

message PaginationRes {
  int32 total_items = 1;
  int32 current_page = 2;
  int32 limit = 3;
  int32 total_pages = 4;
}

// Update User
message UpdateUserReq {
  string user_id = 1;
  optional string first_name = 2;
  optional string last_name = 3;
  optional string email = 4;
  optional string password = 5;
  optional string role = 6;
}

message UpdateUserRes {
  string status = 1;
  UserRes data = 2;
}

// Create User
message CreateUserReq {
  string first_name = 1;
  string last_name = 2;
  string email = 3;
  string password = 4;
  string role = 5;
}

message CreateUserRes {
  string status = 1;
  UserRes data = 2;
}

// Register User
message RegisterUserReq {
  string first_name = 1;
  string last_name = 2;
  string email = 3;
  string password = 4;
  string password_confirm = 5;
}


// Common
message UserRes{
  string id = 1;
  string first_name = 2;
  string last_name = 3;
  string email = 4;
  string role = 5;
  string created_at = 6;
  string updated_at = 7;
}
  