syntax = "proto3";

option csharp_namespace = "TaskFlow.UserService";

package project_service;


import "google/api/annotations.proto"; // Import Google API annotations


// Define the gRPC service
service UserService {
  rpc CreateUser (CreateUserReq) returns (CreateUserRes) {
    option (google.api.http) = {
      post: "/v1/users"
      body: "*"
    };
  }
}

// Define request message
message CreateUserReq {
  string firstName = 1;
  string lastName = 2;
  string email = 3;
  string password = 4;
  string role = 5;
}

// Define response message
message CreateUserRes {
  string status = 1;
  UserRes data = 2;
}


message UserRes{
  string firstName = 1;
  string lastName = 2;
  string email = 3;
  string role = 4;
}