// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.5
//   protoc               v3.21.12
// source: notification.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "notification_service";

export interface CreateNotificationReq {
  recipientId: string;
  actorId?: string | undefined;
  type: string;
  referenceId?: string | undefined;
  referenceType?: string | undefined;
  content?: string | undefined;
  isRead: boolean;
}

export interface CreateNotificationRes {
  status: string;
  message: string;
  data: NotificationRes | undefined;
}

export interface NotificationRes {
  recipientId: string;
  actorId: string;
  type: string;
  referenceId: string;
  referenceType: string;
  content: string;
  isRead: boolean;
  createdAt: string;
}

export const NOTIFICATION_SERVICE_PACKAGE_NAME = "notification_service";

export interface NotificationServiceClient {
  sendNotification(request: CreateNotificationReq): Observable<CreateNotificationRes>;
}

export interface NotificationServiceController {
  sendNotification(
    request: CreateNotificationReq,
  ): Promise<CreateNotificationRes> | Observable<CreateNotificationRes> | CreateNotificationRes;
}

export function NotificationServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["sendNotification"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("NotificationService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("NotificationService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const NOTIFICATION_SERVICE_NAME = "NotificationService";
