// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.5
//   protoc               v3.21.12
// source: notification_service/notification.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";
import { PaginationRes } from "../base";

export const protobufPackage = "notification_service";

export interface GetAllNotificationsReq {
  userId?: string | undefined;
  projectId?: string | undefined;
  sprintId?: string | undefined;
  page?: number | undefined;
  limit?: number | undefined;
}

export interface GetAllNotificationsRes {
  status: string;
  message: string;
  pagination: PaginationRes | undefined;
  data: NotificationRes[];
}

export interface CreateNotificationReq {
  recipientId: string;
  actorId?: string | undefined;
  type: string;
  referenceId?: string | undefined;
  referenceType?: string | undefined;
  content?: string | undefined;
  isRead: boolean;
}

export interface CreateNotificationRes {
  status: string;
  message: string;
  data: NotificationRes | undefined;
}

export interface NotificationRes {
  recipientId: string;
  actorId: string;
  type: string;
  referenceId: string;
  referenceType: string;
  content: string;
  isRead: boolean;
  createdAt: string;
}

export const NOTIFICATION_SERVICE_PACKAGE_NAME = "notification_service";

export interface NotificationServiceClient {
  sendNotification(request: CreateNotificationReq): Observable<CreateNotificationRes>;

  getAllNotifications(request: GetAllNotificationsReq): Observable<GetAllNotificationsRes>;
}

export interface NotificationServiceController {
  sendNotification(
    request: CreateNotificationReq,
  ): Promise<CreateNotificationRes> | Observable<CreateNotificationRes> | CreateNotificationRes;

  getAllNotifications(
    request: GetAllNotificationsReq,
  ): Promise<GetAllNotificationsRes> | Observable<GetAllNotificationsRes> | GetAllNotificationsRes;
}

export function NotificationServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["sendNotification", "getAllNotifications"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("NotificationService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("NotificationService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const NOTIFICATION_SERVICE_NAME = "NotificationService";
