// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v3.21.12
// source: task/search_task.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearchTaskReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchTaskReq) Reset() {
	*x = SearchTaskReq{}
	mi := &file_task_search_task_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchTaskReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchTaskReq) ProtoMessage() {}

func (x *SearchTaskReq) ProtoReflect() protoreflect.Message {
	mi := &file_task_search_task_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchTaskReq.ProtoReflect.Descriptor instead.
func (*SearchTaskReq) Descriptor() ([]byte, []int) {
	return file_task_search_task_proto_rawDescGZIP(), []int{0}
}

func (x *SearchTaskReq) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type SearchTaskRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *Task                  `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchTaskRes) Reset() {
	*x = SearchTaskRes{}
	mi := &file_task_search_task_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchTaskRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchTaskRes) ProtoMessage() {}

func (x *SearchTaskRes) ProtoReflect() protoreflect.Message {
	mi := &file_task_search_task_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchTaskRes.ProtoReflect.Descriptor instead.
func (*SearchTaskRes) Descriptor() ([]byte, []int) {
	return file_task_search_task_proto_rawDescGZIP(), []int{1}
}

func (x *SearchTaskRes) GetData() *Task {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_task_search_task_proto protoreflect.FileDescriptor

var file_task_search_task_proto_rawDesc = string([]byte{
	0x0a, 0x16, 0x74, 0x61, 0x73, 0x6b, 0x2f, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x5f, 0x74, 0x61,
	0x73, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x74, 0x61, 0x73, 0x6b, 0x1a, 0x0f,
	0x74, 0x61, 0x73, 0x6b, 0x2f, 0x74, 0x61, 0x73, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x28, 0x0a, 0x0d, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x71,
	0x12, 0x17, 0x0a, 0x07, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x22, 0x2f, 0x0a, 0x0d, 0x53, 0x65, 0x61,
	0x72, 0x63, 0x68, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x73, 0x12, 0x1e, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x74, 0x61, 0x73, 0x6b, 0x2e,
	0x54, 0x61, 0x73, 0x6b, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x42, 0x05, 0x5a, 0x03, 0x2f, 0x70,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_task_search_task_proto_rawDescOnce sync.Once
	file_task_search_task_proto_rawDescData []byte
)

func file_task_search_task_proto_rawDescGZIP() []byte {
	file_task_search_task_proto_rawDescOnce.Do(func() {
		file_task_search_task_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_task_search_task_proto_rawDesc), len(file_task_search_task_proto_rawDesc)))
	})
	return file_task_search_task_proto_rawDescData
}

var file_task_search_task_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_task_search_task_proto_goTypes = []any{
	(*SearchTaskReq)(nil), // 0: task.SearchTaskReq
	(*SearchTaskRes)(nil), // 1: task.SearchTaskRes
	(*Task)(nil),          // 2: task.Task
}
var file_task_search_task_proto_depIdxs = []int32{
	2, // 0: task.SearchTaskRes.data:type_name -> task.Task
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_task_search_task_proto_init() }
func file_task_search_task_proto_init() {
	if File_task_search_task_proto != nil {
		return
	}
	file_task_task_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_task_search_task_proto_rawDesc), len(file_task_search_task_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_task_search_task_proto_goTypes,
		DependencyIndexes: file_task_search_task_proto_depIdxs,
		MessageInfos:      file_task_search_task_proto_msgTypes,
	}.Build()
	File_task_search_task_proto = out.File
	file_task_search_task_proto_goTypes = nil
	file_task_search_task_proto_depIdxs = nil
}
