// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v3.21.12
// source: google/api/annotations.proto

/* eslint-disable */

export const protobufPackage = "google.api";

export const GOOGLE_API_PACKAGE_NAME = "google.api";
