syntax = "proto3";

option csharp_namespace = "TaskFlow.IssueService";

package project_service;

import "google/protobuf/empty.proto";
import "google/protobuf/wrappers.proto";
import "google/api/annotations.proto";
import "Base/base.proto";

service IssueService {
  rpc CreateIssue (CreateIssueReq) returns (CreateIssueRes) {
    option (google.api.http) = {
      post: "/api/v1/project/{project_id}/issues"
      body: "*"
    };
  }
  rpc GetIssue (GetIssueReq) returns (base.IssueRes) {
    option (google.api.http) = {
      get: "/api/v1/project/{project_id}/issues/{id}"
    };
  }
  rpc UpdateIssue (UpdateIssueReq) returns (base.IssueRes) {
    option (google.api.http) = {
      put: "/api/v1/project/{project_id}/issues/{id}"
      body: "*"
    };
  }
  rpc DeleteIssue (DeleteIssueReq) returns (google.protobuf.Empty) {
    option (google.api.http) = {
      delete: "/api/v1/project/{project_id}/issues/{id}"
    };
  }
  rpc ListIssues (ListIssuesReq) returns (ListIssuesRes) {
    option (google.api.http) = {
      post: "/api/v1/issues/list-issue"
      body: "*"
    };
  }
}

// Get by ID
message GetIssueReq {
  string id = 1;
  string project_id = 2;
}

// Delete by ID
message DeleteIssueReq {
  string id = 1;
  string project_id = 2;
}

//Update
message UpdateIssueReq {
  string id = 1;
  string project_id = 2;    
  optional string sprint_id = 3;
  optional string assignee_id = 4;
  optional string parent_id = 5;
  optional string reporter_id = 6;
  optional string title = 7;
  optional string summary = 8;
  optional string description = 9;
  optional string type = 10;
  optional string column_id = 11;
  optional string priority = 12;
  google.protobuf.Int32Value story_point = 13;
  repeated string attachments = 14;
}

// List All
message ListIssuesReq {
  string project_id = 1;
  repeated string column_ids = 2;
  optional string assingee_id = 3;
  optional string sprint_id = 4;
  optional string keyword = 5;
  int32 page = 6;
  int32 limit = 7;
}

message ListIssuesRes {
  repeated base.IssueRes data = 1;
  base.PaginationRes pagination = 2;
}

// Create
message CreateIssueReq {
  string project_id = 1;
  string title = 2;
  optional string sprint_id = 3;
  optional string assignee_id = 4;
  optional string parent_id = 5;
  optional string reporter_id = 6;
  string type = 7;
  string column_id = 8;
  string priority = 9;
  string summary = 10;
  string description = 11;
  optional int32 story_point = 12;
  repeated string attachments = 13;
}

message CreateIssueRes {
  base.IssueRes data = 1;
}

