// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.5
//   protoc               v3.21.12
// source: base.proto

/* eslint-disable */

export const protobufPackage = "base";

export interface PaginationRes {
  totalItems: number;
  totalPages: number;
  currentPage: number;
  limit: number;
}

export interface ColumnRes {
  id: string;
  name: string;
  createdAt: string;
  updatedAt: string;
  order: number;
  issues: IssueRes[];
  projectId: string;
}

/** Common */
export interface IssueRes {
  id: string;
  title: string;
  projectId: string;
  sprintId: string;
  assigneeId: string;
  parentId: string;
  reporterId: string;
  type: string;
  column: ColumnRes | undefined;
  priority: string;
  summary: string;
  description: string;
  storyPoint: number;
  attachments: string[];
  createdAt: string;
  updatedAt: string;
}

/** Activity */
export interface ActivityRes {
  id: string;
  issueId: string;
  userId: string;
  userName: string;
  actionType: string;
  createdAt: string;
  updatedAt: string;
  changes: ActivityChangesRes[];
}

export interface ActivityChangesRes {
  field: string;
  oldValue: string;
  newValue: string;
}

/** Comment */
export interface CommentRes {
  id: string;
  content: string;
  userId: string;
  issueId: string;
  createdAt: string;
  updatedAt: string;
}

export interface UserRes {
  id: string;
  firstName: string;
  lastName: string;
  email: string;
  role: string;
  createdAt: string;
  updatedAt: string;
}

export const BASE_PACKAGE_NAME = "base";
