// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.5
//   protoc               v3.21.12
// source: media_service/media.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "media_service";

export interface SearchTaskReq {
  taskId: string;
}

export interface SearchTaskRes {
  data: string;
}

export const MEDIA_SERVICE_PACKAGE_NAME = "media_service";

export interface MediaServiceClient {
  uploadImage(request: SearchTaskReq): Observable<SearchTaskRes>;
}

export interface MediaServiceController {
  uploadImage(request: SearchTaskReq): Promise<SearchTaskRes> | Observable<SearchTaskRes> | SearchTaskRes;
}

export function MediaServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["uploadImage"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("MediaService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("MediaService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const MEDIA_SERVICE_NAME = "MediaService";
