// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v3.21.12
// source: media_service/media.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "media_service";

export interface UploadImageReq {
  imageId: string;
}

export interface UploadImageRes {
  url: string;
}

export const MEDIA_SERVICE_PACKAGE_NAME = "media_service";

export interface MediaServiceClient {
  uploadImage(request: UploadImageReq): Observable<UploadImageRes>;
}

export interface MediaServiceController {
  uploadImage(request: UploadImageReq): Promise<UploadImageRes> | Observable<UploadImageRes> | UploadImageRes;
}

export function MediaServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["uploadImage"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("MediaService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("MediaService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const MEDIA_SERVICE_NAME = "MediaService";
