syntax = "proto3";

package chat_service;

service ChatService {
  rpc SendMessage(SendMessageRequest) returns (ChatResponse);
  rpc CreateRoom(CreateRoomRequest) returns (ChatResponse);
  rpc GetMessages(GetMessagesRequest) returns (ChatResponse);
  rpc GetUserRooms(Empty) returns (ChatResponse);
  rpc AddMember(AddMemberRequest) returns (ChatResponse);
  rpc RemoveMember(AddMemberRequest) returns (ChatResponse);
}

message Empty {}

message SendMessageRequest {
  string roomId = 1;
  string content = 2;
  string type = 3;
  optional string replyToId = 4;
}

message CreateRoomRequest {
  optional string name = 1;
  string type = 2;
  repeated string members = 3;
}

message GetMessagesRequest {
  string roomId = 1;
  optional int32 limit = 2;
  optional string before = 3;
}

message AddMemberRequest {
  string roomId = 1;
  string userId = 2;
}

message ChatResponse {
  string status = 1;
  string message = 2;
  bytes data = 3;
}