syntax = "proto3";

option csharp_namespace = "TaskFlow.MetadataService";
package project_service;
import "google/api/annotations.proto";

service MetadataService {
    rpc CreatePresignedURL (CreatePresignedURLReq) returns (CreatePresignedURLRes) {
        option (google.api.http) = {
            post: "/api/v1/metadata/upload"
            body: "*"
        };
    }
    rpc DeleteFile (DeleteFileReq) returns (DeleteFileRes) {
        option (google.api.http) = {
            post: "/api/v1/metadata/delete"
            body: "*"
        };
    }
}

message CreatePresignedURLReq {
    string project_id = 1;
    string user_id = 2;
    string file_name = 3;
    string content_type = 4;
    string upload_type = 5; // "avatar" or "attachment"
}

message CreatePresignedURLRes {
    string presigned_url = 1;
    string file_url = 2;
}

message DeleteFileReq {
    string file_url = 1;
}

message DeleteFileRes {
    bool success = 1;
}
