// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.5
//   protoc               v3.21.12
// source: chat_service/chat.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";
import { ActivityRes, PaginationRes } from "../base";
import { Timestamp } from "../google/protobuf/timestamp";

export const protobufPackage = "chat_service";

export interface SendMessageReq {
  roomId: string;
  content: string;
  type: string;
  replyToId?: string | undefined;
}

export interface SendMessageRes {
  status: string;
  message: string;
  activity: ActivityRes | undefined;
}

export interface CreateRoomReq {
  name?: string | undefined;
  type: string;
  members: string[];
}

export interface CreateRoomRes {
  status: string;
  message: string;
  room: RoomRes | undefined;
}

export interface GetMessagesReq {
  roomId: string;
  limit?: number | undefined;
  before?: Timestamp | undefined;
}

export interface GetMessagesRes {
  status: string;
  message: string;
  pagination: PaginationRes | undefined;
  messages: MessageRes[];
}

export interface GetUserRoomsReq {
  userId?: string | undefined;
}

export interface GetUserRoomsRes {
  status: string;
  message: string;
  rooms: RoomRes[];
}

export interface AddMemberReq {
  roomId: string;
  userId: string;
}

export interface AddMemberRes {
  status: string;
  message: string;
}

export interface RemoveMemberReq {
  roomId: string;
  userId: string;
}

export interface RemoveMemberRes {
  status: string;
  message: string;
}

export interface MessageRes {
  id: string;
  roomId: string;
  senderId: string;
  content: string;
  type: string;
  replyToId?: string | undefined;
  createdAt: Timestamp | undefined;
  updatedAt?: Timestamp | undefined;
}

export interface RoomRes {
  id: string;
  name?: string | undefined;
  type: string;
  members: string[];
  lastMessage?: MessageRes | undefined;
  createdAt: Timestamp | undefined;
  updatedAt?: Timestamp | undefined;
}

export const CHAT_SERVICE_PACKAGE_NAME = "chat_service";

export interface ChatServiceClient {
  sendMessage(request: SendMessageReq): Observable<SendMessageRes>;

  createRoom(request: CreateRoomReq): Observable<CreateRoomRes>;

  getMessages(request: GetMessagesReq): Observable<GetMessagesRes>;

  getUserRooms(request: GetUserRoomsReq): Observable<GetUserRoomsRes>;

  addMember(request: AddMemberReq): Observable<AddMemberRes>;

  removeMember(request: RemoveMemberReq): Observable<RemoveMemberRes>;
}

export interface ChatServiceController {
  sendMessage(request: SendMessageReq): Promise<SendMessageRes> | Observable<SendMessageRes> | SendMessageRes;

  createRoom(request: CreateRoomReq): Promise<CreateRoomRes> | Observable<CreateRoomRes> | CreateRoomRes;

  getMessages(request: GetMessagesReq): Promise<GetMessagesRes> | Observable<GetMessagesRes> | GetMessagesRes;

  getUserRooms(request: GetUserRoomsReq): Promise<GetUserRoomsRes> | Observable<GetUserRoomsRes> | GetUserRoomsRes;

  addMember(request: AddMemberReq): Promise<AddMemberRes> | Observable<AddMemberRes> | AddMemberRes;

  removeMember(request: RemoveMemberReq): Promise<RemoveMemberRes> | Observable<RemoveMemberRes> | RemoveMemberRes;
}

export function ChatServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "sendMessage",
      "createRoom",
      "getMessages",
      "getUserRooms",
      "addMember",
      "removeMember",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("ChatService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("ChatService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const CHAT_SERVICE_NAME = "ChatService";
