// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.5
//   protoc               v5.29.1
// source: google/api/annotations.proto

/* eslint-disable */

export const protobufPackage = "google.api";

export const GOOGLE_API_PACKAGE_NAME = "google.api";
