syntax = "proto3";

option csharp_namespace = "TaskFlow.NotificationService";

package project_service;

import "google/api/annotations.proto";
import "Base/base.proto";

service NotificationService {
  rpc GetUserNotifications(GetUserNotificationsRequest) returns (GetUserNotificationsResponse) {
    option (google.api.http) = {
      get: "/api/v1/notifications"
    };
  }

  rpc GetUnreadNotifications(GetUnreadNotificationsRequest) returns (GetUnreadNotificationsResponse) {
    option (google.api.http) = {
      get: "/api/v1/notifications/unread"
    };
  }

  rpc MarkAsRead(MarkAsReadRequest) returns (NotificationResponse) {
    option (google.api.http) = {
      put: "/api/v1/notifications/{notification_id}/read"
    };
  }

  rpc MarkAllAsRead(MarkAllAsReadRequest) returns (MarkAllAsReadResponse) {
    option (google.api.http) = {
      put: "/api/v1/notifications/read-all"
    };
  }

  rpc GetUnreadCount(GetUnreadCountRequest) returns (GetUnreadCountResponse) {
    option (google.api.http) = {
      get: "  "
    };
  }
}

message GetUserNotificationsRequest {
  int32 page = 1;
  int32 limit = 2;
}

message NotificationResponse {
  base.NotificationRes notification = 1;
}

message GetUnreadNotificationsRequest {}

message MarkAsReadRequest {
  string notification_id = 1;
}

message MarkAllAsReadRequest {}

message GetUnreadCountRequest {}

message GetUserNotificationsResponse {
  repeated base.NotificationRes data = 1;
  base.PaginationRes pagination = 2;
}

message GetUnreadNotificationsResponse {
  repeated base.NotificationRes data = 1;
}

message MarkAllAsReadResponse {
  bool success = 1;
}

message GetUnreadCountResponse {
  int32 count = 1;
}