// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.5
//   protoc               v3.21.12
// source: main_service/notification.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";
import { NotificationRes, PaginationRes } from "../base";

export const protobufPackage = "project_service";

export interface GetUserNotificationsRequest {
  page: number;
  limit: number;
}

export interface NotificationResponse {
  notification: NotificationRes | undefined;
}

export interface GetUnreadNotificationsRequest {
}

export interface MarkAsReadRequest {
  notificationId: string;
}

export interface MarkAllAsReadRequest {
}

export interface GetUnreadCountRequest {
}

export interface GetUserNotificationsResponse {
  data: NotificationRes[];
  pagination: PaginationRes | undefined;
}

export interface GetUnreadNotificationsResponse {
  data: NotificationRes[];
}

export interface MarkAllAsReadResponse {
  success: boolean;
}

export interface GetUnreadCountResponse {
  count: number;
}

export const PROJECT_SERVICE_PACKAGE_NAME = "project_service";

export interface NotificationServiceClient {
  getUserNotifications(request: GetUserNotificationsRequest): Observable<GetUserNotificationsResponse>;

  getUnreadNotifications(request: GetUnreadNotificationsRequest): Observable<GetUnreadNotificationsResponse>;

  markAsRead(request: MarkAsReadRequest): Observable<NotificationResponse>;

  markAllAsRead(request: MarkAllAsReadRequest): Observable<MarkAllAsReadResponse>;

  getUnreadCount(request: GetUnreadCountRequest): Observable<GetUnreadCountResponse>;
}

export interface NotificationServiceController {
  getUserNotifications(
    request: GetUserNotificationsRequest,
  ): Promise<GetUserNotificationsResponse> | Observable<GetUserNotificationsResponse> | GetUserNotificationsResponse;

  getUnreadNotifications(
    request: GetUnreadNotificationsRequest,
  ):
    | Promise<GetUnreadNotificationsResponse>
    | Observable<GetUnreadNotificationsResponse>
    | GetUnreadNotificationsResponse;

  markAsRead(
    request: MarkAsReadRequest,
  ): Promise<NotificationResponse> | Observable<NotificationResponse> | NotificationResponse;

  markAllAsRead(
    request: MarkAllAsReadRequest,
  ): Promise<MarkAllAsReadResponse> | Observable<MarkAllAsReadResponse> | MarkAllAsReadResponse;

  getUnreadCount(
    request: GetUnreadCountRequest,
  ): Promise<GetUnreadCountResponse> | Observable<GetUnreadCountResponse> | GetUnreadCountResponse;
}

export function NotificationServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "getUserNotifications",
      "getUnreadNotifications",
      "markAsRead",
      "markAllAsRead",
      "getUnreadCount",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("NotificationService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("NotificationService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const NOTIFICATION_SERVICE_NAME = "NotificationService";
