// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.5
//   protoc               v3.21.12
// source: main_service/sprint.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";
import { PaginationRes } from "../base";

export const protobufPackage = "project_service";

export interface GetSrintStatsReq {
  sprintId: string;
}

export interface GetSrintStatsRes {
  status: string;
  message: string;
  data: SprintStatData | undefined;
}

export interface SprintStatData {
  sprint: SprintRes | undefined;
  sprintStats: SprintStats | undefined;
  sprintDailyStats: SprintDailyStats[];
}

export interface SprintStats {
  totalIssues: number;
  completedIssues: number;
  totalStoryPoint: number;
  completedStoryPoint: number;
}

export interface SprintDailyStats {
  date: string;
  completedIssues: number;
  remainingIssues: number;
}

/** Sprint Messages */
export interface CreateSprintReq {
  name: string;
  dateStarted: string;
  dateEnded: string;
  duration: number;
  goal: string;
  projectId: string;
}

export interface GetSprintReq {
  id: string;
  projectId: string;
}

export interface UpdateSprintReq {
  id: string;
  name: string;
  dateStarted: string;
  dateEnded: string;
  duration: number;
  goal: string;
  projectId: string;
}

export interface DeleteSprintReq {
  id: string;
  projectId: string;
}

export interface ListSprintsReq {
  projectId: string;
  page: number;
  limit: number;
}

export interface SprintRes {
  id: string;
  name: string;
  dateStarted: string;
  dateEnded: string;
  duration: number;
  goal: string;
  createdAt: string;
  updatedAt: string;
  projectId: string;
}

export interface CreateSprintRes {
  data: SprintRes | undefined;
  pagination?: PaginationRes | undefined;
}

export interface ListSprintsRes {
  data: SprintRes[];
  pagination: PaginationRes | undefined;
}

export interface Empty {
}

export const PROJECT_SERVICE_PACKAGE_NAME = "project_service";

export interface SprintServiceClient {
  createSprint(request: CreateSprintReq): Observable<CreateSprintRes>;

  getSprint(request: GetSprintReq): Observable<SprintRes>;

  updateSprint(request: UpdateSprintReq): Observable<SprintRes>;

  deleteSprint(request: DeleteSprintReq): Observable<Empty>;

  listSprints(request: ListSprintsReq): Observable<ListSprintsRes>;

  getSprintStats(request: GetSrintStatsReq): Observable<GetSrintStatsRes>;
}

export interface SprintServiceController {
  createSprint(request: CreateSprintReq): Promise<CreateSprintRes> | Observable<CreateSprintRes> | CreateSprintRes;

  getSprint(request: GetSprintReq): Promise<SprintRes> | Observable<SprintRes> | SprintRes;

  updateSprint(request: UpdateSprintReq): Promise<SprintRes> | Observable<SprintRes> | SprintRes;

  deleteSprint(request: DeleteSprintReq): Promise<Empty> | Observable<Empty> | Empty;

  listSprints(request: ListSprintsReq): Promise<ListSprintsRes> | Observable<ListSprintsRes> | ListSprintsRes;

  getSprintStats(
    request: GetSrintStatsReq,
  ): Promise<GetSrintStatsRes> | Observable<GetSrintStatsRes> | GetSrintStatsRes;
}

export function SprintServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "createSprint",
      "getSprint",
      "updateSprint",
      "deleteSprint",
      "listSprints",
      "getSprintStats",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("SprintService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("SprintService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const SPRINT_SERVICE_NAME = "SprintService";
