// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.5
//   protoc               v3.21.12
// source: main_service/user.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "project_service";

export interface ChangePasswordReq {
  userId: string;
  oldPassword: string;
  newPassword: string;
}

export interface ChangePasswordRes {
  status: string;
  message: string;
}

export interface GetStatsReq {
  id: string;
  isSprintId: boolean;
}

export interface StatusCount {
  name: string;
  count: number;
}

export interface PriorityCount {
  priority: string;
  count: number;
}

export interface TypeCount {
  type: string;
  count: number;
}

export interface UserStats {
  byStatus: StatusCount[];
  byPriority: PriorityCount[];
  byType: TypeCount[];
  newIssuesCount: number;
  recentlyUpdatedCount: number;
}

export interface GetStatsRes {
  status: string;
  message: string;
  data: UserStats | undefined;
}

/** LogoutUserReq and LogoutUserRes */
export interface LogoutUserReq {
}

export interface LogoutUserRes {
  status: string;
  message: string;
}

/** LOGIN */
export interface LoginUserReq {
  email: string;
  password: string;
}

export interface LoginUserRes {
  status: string;
  message: string;
  data: UserRes | undefined;
}

/** Get user by email */
export interface GetUserByEmailReq {
  email: string;
}

/** Get one user */
export interface GetUserReq {
  userId: string;
}

export interface GetUserRes {
  status: string;
  data: UserRes | undefined;
}

/** List User */
export interface ListUsersReq {
  name?: string | undefined;
  email?: string | undefined;
  userIds: string[];
  page: number;
  limit: number;
}

export interface ListUsersRes {
  status: string;
  data: UserRes[];
  pagination: PaginationRes | undefined;
}

export interface PaginationRes {
  totalItems: number;
  currentPage: number;
  limit: number;
  totalPages: number;
}

/** Update User */
export interface UpdateUserReq {
  userId: string;
  firstName?: string | undefined;
  lastName?: string | undefined;
  email?: string | undefined;
  password?: string | undefined;
  role?: string | undefined;
}

export interface UpdateUserRes {
  status: string;
  data: UserRes | undefined;
}

/** Create User */
export interface CreateUserReq {
  firstName: string;
  lastName: string;
  email: string;
  password: string;
  role: string;
}

export interface CreateUserRes {
  status: string;
  data: UserRes | undefined;
}

/** Register User */
export interface RegisterUserReq {
  firstName: string;
  lastName: string;
  email: string;
  password: string;
  passwordConfirm: string;
}

/** Common */
export interface UserRes {
  id: string;
  firstName: string;
  lastName: string;
  email: string;
  role: string;
  createdAt: string;
  updatedAt: string;
}

export const PROJECT_SERVICE_PACKAGE_NAME = "project_service";

/** Define the gRPC service */

export interface UserServiceClient {
  createUser(request: CreateUserReq): Observable<CreateUserRes>;

  login(request: LoginUserReq): Observable<LoginUserRes>;

  register(request: RegisterUserReq): Observable<CreateUserRes>;

  updateUser(request: UpdateUserReq): Observable<UpdateUserRes>;

  getById(request: GetUserReq): Observable<GetUserRes>;

  getMe(request: GetUserReq): Observable<GetUserRes>;

  getByEmail(request: GetUserByEmailReq): Observable<GetUserRes>;

  listUsers(request: ListUsersReq): Observable<ListUsersRes>;

  logout(request: LogoutUserReq): Observable<LogoutUserRes>;

  getStats(request: GetStatsReq): Observable<GetStatsRes>;

  changePassword(request: ChangePasswordReq): Observable<ChangePasswordRes>;
}

/** Define the gRPC service */

export interface UserServiceController {
  createUser(request: CreateUserReq): Promise<CreateUserRes> | Observable<CreateUserRes> | CreateUserRes;

  login(request: LoginUserReq): Promise<LoginUserRes> | Observable<LoginUserRes> | LoginUserRes;

  register(request: RegisterUserReq): Promise<CreateUserRes> | Observable<CreateUserRes> | CreateUserRes;

  updateUser(request: UpdateUserReq): Promise<UpdateUserRes> | Observable<UpdateUserRes> | UpdateUserRes;

  getById(request: GetUserReq): Promise<GetUserRes> | Observable<GetUserRes> | GetUserRes;

  getMe(request: GetUserReq): Promise<GetUserRes> | Observable<GetUserRes> | GetUserRes;

  getByEmail(request: GetUserByEmailReq): Promise<GetUserRes> | Observable<GetUserRes> | GetUserRes;

  listUsers(request: ListUsersReq): Promise<ListUsersRes> | Observable<ListUsersRes> | ListUsersRes;

  logout(request: LogoutUserReq): Promise<LogoutUserRes> | Observable<LogoutUserRes> | LogoutUserRes;

  getStats(request: GetStatsReq): Promise<GetStatsRes> | Observable<GetStatsRes> | GetStatsRes;

  changePassword(
    request: ChangePasswordReq,
  ): Promise<ChangePasswordRes> | Observable<ChangePasswordRes> | ChangePasswordRes;
}

export function UserServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "createUser",
      "login",
      "register",
      "updateUser",
      "getById",
      "getMe",
      "getByEmail",
      "listUsers",
      "logout",
      "getStats",
      "changePassword",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("UserService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("UserService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const USER_SERVICE_NAME = "UserService";
